### ISSUE TITLE
Add valid range for StepNumber

### ISSUE THREAD

**Issue by aiste-kalinauskaite** [OasisLMF/OpenDataStandards#6] opened 2020-05-29 15:25 UTC
I have missed this, but it is defined in description. Please add [1,10] for valid range (column H) for StepNumber in 'OED Input Fields' tab.

**Comment by MattDonovan82** [comment] 2020-07-01 08:44
This looks like  a simple addition to the data spec.xlsx.
It will be actioned once the process for doc versioning has been confirmed.

**Comment by MattDonovan82** [comment] 2020-07-07 15:07
done and will be included in next release

**Comment by MattDonovan82** [comment] 2020-07-07 15:08
will leave open until next release

**Closed** 2020-07-17 15:30 UTC
